In [6]:
import pandas as pd
df = pd.read_csv("vgsalesGlobale.csv")

tashi_totsales = df["Global_Sales"].sum()
tashi_highsales = df.loc[df["Global_Sales"].idxmax(), ["Name", "Global_Sales"]]
tashi_avgsalesregion = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].mean()
tashi_genres = df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(5)
region_genresales = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
most_popular_genre_na = region_genresales["NA_Sales"].idxmax()
tashi_3platforms = df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(3)
tashi_marketshare = (df.groupby("Genre")["Global_Sales"].sum() / tashi_totsales ) * 100
tashi_corr = df["NA_Sales"].corr(df["EU_Sales"])

print("\t\t\t\t\t______________________")
print("\t\t\t\t\t| Total Global Sales |")
print("\t\t\t\t\t|____________________|")
print("\n\n")
print(tashi_totsales)
print("\t\t\t\t\t________________________")
print("\t\t\t\t\t| Highest Selling Game |")
print("\t\t\t\t\t|______________________|")
print("\n\n")
print(tashi_highsales)
print("\t\t\t\t\t___________________________")
print("\t\t\t\t\t| Average Sales by Region |")
print("\t\t\t\t\t|_________________________|")
print("\n\n")
print(tashi_avgsalesregion)
print("\t\t\t\t\t_____________________________")
print("\t\t\t\t\t| Top 5 Most Popular Genres |")
print("\t\t\t\t\t|___________________________|")
print("\n\n")
print(tashi_genres)
print("\t\t\t\t\t____________________________")
print("\t\t\t\t\t| Most Popular Genre in NA |")
print("\t\t\t\t\t|__________________________|")
print("\n\n")
print("Most Popular Genre in NA:", most_popular_genre_na)
print("\t\t\t\t\t__________________________")
print("\t\t\t\t\t| Top 3 Gaming Platforms |")
print("\t\t\t\t\t|________________________|")
print("\n\n")
print(tashi_3platforms)
print("\t\t\t\t\t_________________________")
print("\t\t\t\t\t| Market Share by Genre |")
print("\t\t\t\t\t|_______________________|")
print("\n\n")
print(tashi_marketshare)
print("\t\t\t\t\t____________________________________________")
print("\t\t\t\t\t| Correlation between NA Sales and EU Sales|")
print("\t\t\t\t\t|__________________________________________|")
print("\n\n")
print(tashi_corr)
print("\t\t\t\t\t________________")
print("\t\t\t\t\t| Last 10 Rows |")
print("\t\t\t\t\t|______________|")
print("\n\n")
print(df.tail(10))

					______________________
					| Total Global Sales |
					|____________________|



8920.44
					________________________
					| Highest Selling Game |
					|______________________|



Name            Wii Sports
Global_Sales         82.74
Name: 0, dtype: object
					___________________________
					| Average Sales by Region |
					|_________________________|



NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
					_____________________________
					| Top 5 Most Popular Genres |
					|___________________________|



Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
					____________________________
					| Most Popular Genre in NA |
					|__________________________|



Most Popular Genre in NA: Action
					__________________________
					| Top 3 Gaming Platforms |
					|________________________|



Platform
PS2    

In [8]:
print("\t\t\t\t\t______________________________")
print("\t\t\t\t\t| English-Spanish Dictionary |")
print("\t\t\t\t\t|____________________________|")
print("\n\n")
tashi_dict = {
    "hello": "hola",
    "world": "mundo",
    "goodbye": "adios",
    "please": "por favor",
    "thank you": "gracias",
    "yes": "sí",
    "no": "no",
    "food": "comida",
    "water": "agua",
    "friend": "amigo",}

while True:
    tashi_word = input("Enter word (Type 'exit' to quit): ").lower()
    if tashi_word == "exit":
        break
    if tashi_word in tashi_dict:
        print(f"Translation: {tashi_dict[tashi_word]}")
        print("\n")
    else:
        print(f"No translation")
        print("\n")

					______________________________
					| English-Spanish Dictionary |
					|____________________________|



Enter word (Type 'exit' to quit): thank you
Translation: gracias


Enter word (Type 'exit' to quit): quit
No translation


Enter word (Type 'exit' to quit): exit


In [16]:
def classify_emails():
    important_emails = []
    promotion_emails = []
    spam_emails = []

    tashi_email = [
        "FED watch meeting at 12 am.  ",
        "Soso coin offer alot of discounts. ",
        "You are good and best"
        "Crypto money deals in the best money making",
        "Urgently require Person to eat pizza :)",
        "DGKC will go down. "
    ]

    tashi_imp = ["meeting", "urgent", "crypto"]
    tashi_pro = ["discount", "offer", "deals", "sale"]
    tashi_spam = ["go", "best", "good", "down"]

    for i in tashi_email:
        email_lower = i.lower()
        if any(keyword in email_lower for keyword in tashi_imp):
            important_emails.append(i)
        elif any(keyword in email_lower for keyword in tashi_pro):
            promotion_emails.append(i)
        elif any(keyword in email_lower for keyword in tashi_spam):
            spam_emails.append(i)
        else:
            important_emails.append(i)

    print("\t\t\t\t\t______________________")
    print("\t\t\t\t\t| Important Emails   |")
    print("\t\t\t\t\t|____________________|")
    print("\n\n")
    for email in important_emails:
        print(f"{email}")

    print("\t\t\t\t\t_________________________")
    print("\t\t\t\t\t| Promotions Emails     |")
    print("\t\t\t\t\t|_______________________|")
    print("\n\n")
    for email in promotion_emails:
        print(f"{email}")

    print("\t\t\t\t\t____________________")
    print("\t\t\t\t\t| Spam Emails      |")
    print("\t\t\t\t\t|__________________|")
    print("\n\n")
    for email in spam_emails:
        print(f"{email}")

classify_emails()

					______________________
					| Important Emails   |
					|____________________|



FED watch meeting at 12 am.  
You are good and bestCrypto money deals in the best money making
Urgently require Person to eat pizza :)
					_________________________
					| Promotions Emails     |
					|_______________________|



Soso coin offer alot of discounts. 
					____________________
					| Spam Emails      |
					|__________________|



DGKC will go down. 


In [24]:
def online_store():
    print("\t\t\t\t\t_____________________________________")
    print("\t\t\t\t\t| Welcome to Tashi Online Stores    |")
    print("\t\t\t\t\t|___________________________________|")
    print("\n\n")
    shopping_cart = []

    tashi_products = {
        1: "AI Response Simulator",
        2: "Investment Decision",
        3: "Data Analytics Toolkit"
    }

    for i,j in tashi_products.items():
        print(f"{i}. {j}")
    print("Type exit to checkout.")
    print("\n")
    while True:
        choice = input("Select: (or 'exit' to checkout): ").lower()

        if choice == 'exit':
            print("Checking out :(")
            print("\n")
            break
        if choice.isdigit():
            choice = int(choice)
            if choice in tashi_products:
                shopping_cart.append(tashi_products[choice])
                print(f"Added '{tashi_products[choice]}' to shopping cart.")
                print("\n")
            else:
                print("Select a product.")
        else:
            print("Please enter a number or 'q' to quit.")

    if shopping_cart:
        print("\t\t\t\t\t___________________")
        print("\t\t\t\t\t|  Shopping Cart  |")
        print("\t\t\t\t\t|_________________|")
        print("\n\n")
        for item in shopping_cart:
            print(f"- {item}")
    else:
        print("Shopping cart Empty")

    print("\n")
    print("Thank you for shopping. Bu bu")

online_store()

					_____________________________________
					| Welcome to Tashi Online Stores    |
					|___________________________________|



1. AI Response Simulator
2. Investment Decision
3. Data Analytics Toolkit
Type exit to checkout.


Select: (or 'exit' to checkout): 1
Added 'AI Response Simulator' to shopping cart.


Select: (or 'exit' to checkout): 3
Added 'Data Analytics Toolkit' to shopping cart.


Select: (or 'exit' to checkout): 2
Added 'Investment Decision' to shopping cart.


Select: (or 'exit' to checkout): 1
Added 'AI Response Simulator' to shopping cart.


Select: (or 'exit' to checkout): exit
Checking out :(


					___________________
					|  Shopping Cart  |
					|_________________|



- AI Response Simulator
- Data Analytics Toolkit
- Investment Decision
- AI Response Simulator


Thank you for shopping. Bu bu


In [27]:
import numpy as np

tashi_arr1 = np.array([1, 2, 3, 4, 5])
tashi_arr2 = np.array([10, 20, 30, 40, 50])

addition_result = tashi_arr1 + tashi_arr2
product_result = tashi_arr1 * tashi_arr2

print("Array 1:", tashi_arr1)
print("Array 2:", tashi_arr2)
print("\n")
print("Addition: ", addition_result)
print("Product: ", product_result)


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]


Addition:  [11 22 33 44 55]
Product:  [ 10  40  90 160 250]


In [28]:
import numpy as np
tashi_array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
tashi_array2d = tashi_array1d.reshape(3, 4)

array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[7, 8, 9], [10, 11, 12]])

horizontal_concat = np.hstack((array_a, array_b)) #h
vertical_concat = np.vstack((array_a, array_b))#v

print(" 1D Array:", tashi_array1d)
print("Reshape 2D Array :\n", tashi_array2d)
print("Array A:\n", array_a)
print("Array B:\n", array_b)
print("Horizontally Concatenated Array:\n", horizontal_concat)
print("Vertically Concatenated Array:\n", vertical_concat)

 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape 2D Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array A:
 [[1 2 3]
 [4 5 6]]
Array B:
 [[ 7  8  9]
 [10 11 12]]
Horizontally Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically Concatenated Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
tashi_o = [1, 2, 3, 4, 5]
tashi_r = tashi_o[::-1]
print("Original List:", tashi_o)
print("\n")
print("Reversed List:", tashi_r)

Original List: [1, 2, 3, 4, 5]


Reversed List: [5, 4, 3, 2, 1]
